name: Changeset existence
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    changeset:
        name: Build, test & lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install pnpm 8.6.12
              uses: pnpm/action-setup@v4.0.0
              with:
                  version: 8.6.12

            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            - name: Build, test & lint
              run: pnpm turbo run lint build test --filter=...[main...HEAD]
